---

- name: Install for debian
  ansible.builtin.import_tasks: pkg-debian.yml
  when: ansible_os_family == "Debian"

- name: Install for RedHat
  ansible.builtin.import_tasks: pkg-redhat.yml
  when: ansible_os_family == "RedHat"
