---

- name: Add rpm repository key
  rpm_key:
    state: present
    key: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x24765BBD8E16EB44

- set_fact:
    distribution_repository_name: centos
  when: ansible_distribution != 'Fedora'

- set_fact:
    distribution_repository_name: fedora
  when: ansible_distribution == 'Fedora'

- name: Install redirection.io repository
  yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "https://packages.redirection.io/rpm/{{ distribution_repository_name }}_{{ ansible_distribution_major_version }}"
    enabled: yes
    gpgcheck: yes
    state: present

- name: Update yum cache
  yum:
    update_cache: true

- name: Install libnginx-mod-redirectionio
  yum:
    name: libnginx-mod-redirectionio
    state: latest
