---

- name: Add rpm repository key
  rpm_key:
    state: present
    key: "{{ redirectionio_gpg_key_url }}"

- name: Define distribution_repository_name
  set_fact:
    distribution_repository_name: centos
  when: ansible_distribution != 'Fedora'

- name: Define distribution_repository_name when the distribution is Fedora
  set_fact:
    distribution_repository_name: fedora
  when: ansible_distribution == 'Fedora'

- name: Install redirection.io repository
  yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "{{ redirectionio_packages_url }}rpm/{{ distribution_repository_name }}_{{ ansible_distribution_major_version }}"
    enabled: yes
    gpgcheck: yes
    state: present

- name: Update yum cache
  yum:
    update_cache: true

- name: Install libnginx-mod-redirectionio
  yum:
    name: libnginx-mod-redirectionio
    state: present
